### ISSUE TITLE
Example of hover effect in documentation

### ISSUE THREAD

**Issue by annetawamono** [markmead/custom-cursor#16]
Hello,

Could you add an example of how to create a hover effect in the docs. I've been trying a couple of different ways but I haven't gotten it to work.

Thanks for this repo, it's been really helpful.

Cheers!

**Comment by markmead** [comment]
Hey, @annetawamono there's an example at the bottom of this section - https://github.com/markmead/custom-cursor#targets, but maybe it's not enough detail. For now, I'll give you a quick write-up.

If you have custom cursor setup like this:

```js
new Cursor({
  count: 5,
  targets: [".hover-me", "a"],
})
```

And in your HTML you have this markup:

```html
<body>
  <h1>Hello there</h1>
  
  <a href="#">Something</a>
  
  <div class="hover-me"></div>
</body>
```

Then the CSS you can write to target the custom cursor when `.hover-me` and/or `a` targets are "mouseover" is:

```
.cursor-hover--hover-me [data-cursor] { }
.cursor-hover--a [data-cursor] { }
```

It works by adding `cursor-hover--<target>` to the body tag in the HTML.

Hopefully that makes sense.

**Comment by markmead** [comment]
Got a refreshed version of this package on this PR #17 which will include these snippets.
