### ISSUE TITLE
Feature Request: Add Easing

### ISSUE THREAD

**Issue by elijah-io** [markmead/custom-cursor#7]
A request to add easing to the way the mouse follows you.

Similar to this:
<img src="https://github.com/gaoryrt/cursor-dot/raw/master/smoothcursorfollowing.gif"></img>

[This code](https://github.com/gaoryrt/cursor-dot/blob/master/index.js) may be helpful (it's what's used in that GIF). I'm struggling to implement so I'm looking for help with this feature.

Adding transition-properties in CSS doesn't work because it creates a weird delay even though the `top` and `left` properties are being updated in realtime.

Love your work and the simplicity of this package. Thank you @markmead!

**Comment by markmead** [comment]
Great idea @elijah-io! I appreciate the feedback.

As for the example given, it only uses the `transition-duration` CSS. This is something you can easily replicate - [CodePen example](https://codepen.io/markmead/pen/jOPmRRe).
